name: Deploy EduPaie
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - run: |
          npm install
          npm run build
          
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.1
        with:
          server: ftp.tanmiton.com
          username: tanmi2503002
          password: Klouya123@
          local-dir: ./dist/
          server-dir: /edupaie.tanmiton.com/  # Chemin RELATIF depuis la racine FTP
          protocol: ftp
          server-root: /  # Spécifie que la racine FTP est le point de départ
          dangerous-clean-slate: false
          exclude: |
            .git/
            .github/
            *.md
            node_modules/
